version: "3.9"
services:
  ffmpeg_queue:
    container_name: ffmpeg-queue
    build: .
    ports: 
      - "3000:3000"
    links:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "yarn install && 
      yarn global add nodemon && 
      apk update && 
      apk add inotify-tools && 
      nodemon start"
  redis:
    container_name: ffmpeg-queue-redis
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"